# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nSduOndAJhvo34-oPd2WyOcb5488alCR
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Define the seed for reproducibility
seed = 42

# Read original dataset
iris_df = pd.read_csv('Iris.csv')
iris_df = iris_df.sample(frac=1, random_state=seed)  # Perhatikan bahwa hasil fungsi sample harus disimpan kembali ke DataFrame

# Memilih fitur dan data target
X = iris_df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = iris_df['Species']  # Memperbaiki pemilihan kolom target

# Membagi data menjadi set latihan dan uji
# 70% latihan dan 30% uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=seed, stratify=y)

# Membuat sebuah instance dari klasifikasi Random Forest
clf = RandomForestClassifier(n_estimators=100)

# Melatih klasifikasi pada data latihan
clf.fit(X_train, y_train)

# Memprediksi pada set uji
y_pred = clf.predict(X_test)

# Menghitung akurasi
accuracy = accuracy_score(y_test, y_pred)
print(f'Akurasi: {accuracy}')

# save the model to disk
import joblib
joblib.dump(clf, 'rf_model.sav')